version: '3.8'

services:
  app:
    image: maven:3.9.11-eclipse-temurin-17
    container_name: insurance-app
    working_dir: /app
    volumes:
      - ./:/app
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: insurance-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
